assetpost/urls.py
from django.conf.urls import patterns, url
from rest_framework.routers import DefaultRouter
from .views import PostEntryUpdate, PageCreate, updatePage, createEntry, updateEntry, multipost, multipost_init, DefaultsMixin, EntryViewSet

router = DefaultRouter()
router.register(r'entries', EntryViewSet)


urlpatterns = patterns('',
#    url(r'^newpostentry/', PostEntryCreate.as_view(), name='post_entry'),
    url(r'^newpostpage/', PageCreate.as_view(), name='postpage'),
    url(r'^updatepostentry/(?P<pk>\w+)/$', PostEntryUpdate.as_view(), name='update_entry'),
    url(r'^updatepage/(?P<id>\w+)/$', updatePage, name='updatePage'),
    url(r'^create-entry/', createEntry, name='createEntry'),
    url(r'^update-entry/(?P<id>\w+)/$', updateEntry, name='updateEntry'),
    url(r'^multipost/', multipost, name='multipost'),
    url(r'^multipost-init/(?P<client>\w+)/(?P<id>\w+)/$', multipost_init, name='multipost-initial'),

)

dapprj/urls.py
from django.conf import settings
from django.contrib import admin
from assetpost.views import *
from filebrowser.sites import site
from django.conf.urls import include, url
from rest_framework.authtoken.views import obtain_auth_token

from assetpost.urls import router

if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'^api/', include(router.urls)),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', login_user, name='login_user'),
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
    url(r'^main/', postsearch),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
    url(r'^filebrowser/', file_browser),
    url(r'^assetpost/', include('assetpost.urls', namespace='assetpost', app_name='assetpost')),
    url(r'^upload/', file_upload),
    url(r'^quickpost/(?P<job_number>[A-Z0-9-]+)/', quickpost, name="quickpost"),
    url(r'^taskmanager/', include('taskmanager.urls', namespace="taskmanager")),
    url(r'^specdisplay/(?P<job_number>[A-Z0-9-]+)/', display_record, name="display_record"),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
]
urlpatterns += (
   url(r'^__debug__/', include(debug_toolbar.urls)),
)

templates/admin_filebrowser.html
{% extends "base.html" %}

		{% block title %} AssetPost | Filebrowser {% endblock %}
	 
		{% block head_content %}
    
        {%  endblock %}

		{% block content %}
            <iframe id="inbox_frame" src="" width="100%" height="100%"></iframe>
			<iframe id="fb_frame" src="{{ base_url }}/admin/filebrowser/browse/" border="0" height="1080" width="100%" seamless="seamless" overflow="hidden" scrolling="yes" style="margin-top:15px;"></iframe>
 



		{% endblock %}


templates/admin_frame.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title>{% block title %}{% endblock %}</title> 
		<link>{% block link %}{% endblock %}</link>
		<link rel="stylesheet" type="text/css" href="../../../../site_media/css/wrmscurrent.css" />
	<!--	<link rel="stylesheet" type="text/css" href="../../../../site_media/css/custom-theme/BUjquery-ui-1.8.1.custom.css" /> 
	    <link rel="stylesheet" href="../../../../site_media/css/themes/blue/style.css" type="text/css" media="print, projection, screen" /> -->
		

		<script>{% block script %}{% endblock %}</script>
		<script src="http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js"></script> 
		<script src="http://code.jquery.com/jquery-1.9.0.js"></script>
		<script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>
		<script type="text/javascript" language="javascript" src="../../../../site_media/js/jquery-ui-1.7.2.custom.min.js"></script>
		<script type="text/javascript" language="javascript" src="../../../../site_media/js/jquery.tablesorter.min.js"></script> 
		<script type="text/javascript" language="javascript" src="../../../../site_media/js/jquery.tablesorter.pager.js"></script> 
		<script type="text/javascript" language="javascript" src="../../../../site_media/js/jquery.metadata.js"></script> 
	<!--<script src="../../../../site_media/js/wrms_portal.js" type="text/javascript" charset="utf-8"></script> -->
		<!--[if IE 8]><script>
document.getElementsByClassName = 
Element.prototype.getElementsByClassName = function(class_name) {
    // Escape special characters
    class_name = (class_name + '').replace(/[~!@$%^&*()_+\-=,./';:"?><[\]{}|`#]/g, '\\$&');
    return this.querySelectorAll('.' + class_name);
};
</script><![endif]-->
<script type="text/javascript">

function showInbox(){
  var user = "{{ user.last_name }}";
  if (user){
    document.getElementById('quickpost_button').style.display = "block";
  }else{
    document.getElementById('quickpost_button').style.display = "none";
  }
}
function showDashboard(url) {
	$('.shell').css('margin', '0');
	$('#logo_wedb').css('visibility', 'hidden');
	$('#stage').fadeOut( "fast", function() { });
	$('#inbox_frame').fadeIn(4000, function() { });
	
//	newwindow=window.open(url,'WRMS | Project Inbox','height=700, width=1200,top=20,left=0,resizable');
//	if (window.focus) {newwindow.focus()}
}
</script>

<style type="text/css">
#quickpost_button{ position:absolute; display:none; top:10px;left:600px;cursor:pointer; width:400px; height:54px;}
html{overflow:hidden;}
a { color: #333; }
body{margin:0;}
input.qp_inp{
	width:80px;height:14px;font-size:1.1em;margin-top:0;
}
#InboxEntry_button{ position:absolute; display:none; top:10px;left:600px;cursor:pointer; width:65px; height:22px;}
#inbox_frame{ position:absolute; display:none; top:50px;left:0;width:1600px;height:1200px;z-index:5500;}
</style>
<style>{% block style %}{% endblock %}</style>
</head>

<body>
	
		<div id="nav">
			<div class="wrap"> 
				<div class="menu">  
					<a class="menu-item menu-item-support" href="../../main/"><span class="current" style="margin-right:0;">{{ user.first_name }}&nbsp;{{ user.last_name }}</span></a>
					<a class="menu-item menu-item-about" href="#"><span class="label">Pages</span></a> 
					<a class="menu-item menu-item-developer" href="#"></span><span class="label">Entries</span></a> 
					<a class="menu-item menu-item-community" href="../../filebrowser/"><span class="label">Filebrowser</span></a> 
					<a class="menu-item menu-item-app" href="/../../contact/internal/"><span class="label">Contact</span></a> 
					 
						<!--<div class="menu-item menu-item-download"> 
							<a class="bt accent" href="/download#autodownload"> <span class="icon i-download"> </span><span class="label">Download</span> </a> 
						</div>  -->
				</div>
				<div class="dropdown dropdown-about"> 
					<div class="inner"> 
						<a href="../../newpostpage/">Create Post Page</a> 
						<a href="../../newportalpage/">Create Portal Page</a> 
						<a href="../../newtacticpage/">Create Tactic Page</a>
						<a href='../../newbannerpage/'>create Banner Page</a> 
					</div> 
				</div> 
				<div class="dropdown dropdown-developer"> 
					<div class="inner"> 
						<a href="../../newpostentry/">Post to Project</a> 
						<a href="../../newtacticentry/">Post to Tactic</a> 
					</div> 
				</div> 
				<div class="dropdown dropdown-community"> 
					<div class="inner"> 
						<a href="../../filebrowser/">Filebrowser</a> 
					</div> 
				</div> 
				<div class="dropdown dropdown-app"> 
					<div class="inner"> 
						<a class='inactive' href="/../../contact/internal/">Contact Sheet</a>  
					</div> 
				</div> 
				<div class="dropdown dropdown-support"> 
					<div class="inner">  
					<!--	<a class='inactive' href='../../leave_request/{{ user.userprofile.id }}'>Leave Requests / Records</a> -->
						<a class='inactive' href='/../logout/'>Logout</a>
					</div> 
				</div>
			</div>	
		  </div>
			<script type="text/javascript">
			function processJobNumber(){
				var input = $('#job_id').val();
				var input = input.toUpperCase();
				if (input.length < 8 || input.length > 15) {
					alert ("Please input a valid job number");
				}else {
				var href =  "../../quickpost/" + input;
				function showPopup(url) {
					newwindow=window.open(url,'WRMS | QuickPost','height=900, width=1600,top=20,left=0,resizable');
					if (window.focus) {newwindow.focus()}
				}
				showPopup(href);
				}
			}
			function processBranding(){
				var input = $('#job_id').val();
				if (input.length < 1) {
					alert ("Please input a client name");
				}else {
				var href =  "../../branding/" + input;
				function brandingPopup(url) {
					newwindow=window.open(url,'WRMS | BrandingColors','height=400, width=900,top=20,left=0,resizable');
					if (window.focus) {newwindow.focus()}
				}
				brandingPopup(href);
				}
			}
			
			</script>
			<div id="quickpost_button"><input type="text" id="job_id" class="qp_inp" /><a id="job_id_link" href="../../quickpost/" onclick="processJobNumber();return(false);" /><img  width="65" height="22" src="../../../../site_media/images/quickpost_btn.png" /></a><a href="../../production-display/{{ user.userprofile.id }}" onclick="showDashboard(this.href);return(false);"><img  width="65" height="22" src="../../../../site_media/images/inbox_btn.png" /></a>
			<a id="job_id_link" href="../../branding/" onclick="processBranding();return(false);" /><img  width="65" height="22" src="../../../../site_media/images/branding_btn.png" /></a>
			</div>
			</div>
			
			<script type="text/javascript">

		function activateDropDown(target, height) {
		    var animate = true;
		    var prefix = '.dropdown-' + target;
		    var menuPrefix = '.menu-item-' + target;
		    var menu = $(prefix);
		    var height = 0;
		    height = $(prefix + ' .inner').height()+4+4+8;

		    $(prefix +', ' + '.menu-item-' + target).hover(function(r){
		        var item = $(this);
		        if (item[0].className && item[0].className.indexOf('menu') > -1) {
		            var left = item.position().left;
		            menu.css('left', left+'px');
		            menu.clearQueue().animate({height:height+'px'}, 200);
		            $(menuPrefix).addClass('active')
		        }
		        animate = false;
		        setTimeout(function(){animate = true;},1);
		        menu.css('display', 'block');
		    }, function(r) {
		        setTimeout(function(){
		            if (animate) {
		                menu.animate({height:'0px'}, 200);
		                $(menuPrefix).removeClass('active');
		            }
		        }, 0);
		    });
		}

		    activateDropDown('about'); 

		    activateDropDown('developer'); 

		    activateDropDown('community'); 

		    activateDropDown('app'); 

		    activateDropDown('support'); 
		
			showInbox();

		</script>
		
	{% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</body>
</html>

templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
       
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-table.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script>
        function multiPost(url){
            var input = $('#job_id').val();
            var input = input.toUpperCase();
            var client = $('#client_select').find(":selected").attr('id');
            if (input.length < 8 || input.length > 15) {
                alert ("Please input a valid job number");
            }else if (client == "null_option"){
                alert ("Please choose a client from the dropdown menu at left");
            }else{
                
                
            var href ='{{ base_url }}/assetpost/multipost-init/' + client + '/' + input ;
            window.location = href;
            }
        }
       </script>
            {% block head_content %}{% endblock %}

    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <time></time>
                <a class="navbar-brand" href="/main/">AssetPost</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.first_name }}&nbsp;{{ user.last_name }}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "django.contrib.auth.views.logout" %}?next=/" class="">logout</a></li>
                        </ul>
                    </li>


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'assetpost:postpage' %}" class="">create posting page</a></li>
                            <li><a href="{% url 'assetpost:createEntry' %}" class="">add entry</a></li>
                            <li><a href="{% url 'assetpost:multipost' %}" class="">multipost</a></li>
                        </ul>
                    </li>
                    <li><a href="{{ base_url }}/filebrowser/">Filebrowser</a></li>
                </ul> 
                
                <form class="navbar-form navbar-right" role="form">
                    {% if clients %}
                    <div class="form-group">
                        <select name="client_select" id="client_select">
                            <option id="null_option">---------</option>
                            {% for client in clients %}
                            <option id="{{ client.id }}">{{ client.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <input id="job_id" type="text" placeholder="project id" class="form-control">
                    </div>
                    <button type="submit" id="qp_button" href="{{ base_url }}/quickpost/" class="btn btn-success" name="quickpost" onclick="processJobNumber();return(false);">QuickPost
                    </button>
                    <button type="submit" href="{{ base_url }}/multipost/" class="btn btn-success" name="multipost" onclick="multiPost();return(false);">MultiPost
                    </button>
                    <button id="inbox_button" href="{{ base_url }}/taskmanager/display/{{ user.userprofile.id }}/" class="btn btn-success" onclick="showDashboard();return(false);">TaskManager
                    </button> 
                </form>
            </div><!--/.navbar-collapse -->
    </nav>
    
      {% block content %}{% endblock %}

      <footer>
        <div class="container">
        </div>
      </footer>
        

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. 
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        -->
    </body>
</html>

templates/base_nonav.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
       
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
            {% block head_content %}{% endblock %}

    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    
      {% block content %}{% endblock %}

      <footer>
        <div class="container">
        </div>
      </footer>
        

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. 
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        -->
    </body>
</html>

templates/createpostpage.html
{% extends "base.html" %}
	 
		

		{% block content %}

		{% load crispy_forms_tags %}
        {% crispy form %}


		{% endblock %}


templates/email_signup.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <p>Hi {{ user }}!,</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero qui natus, doloremque dolorem aspernatur, expedita debitis repudiandae in. Ex est, fugiat ipsa iusto. Nesciunt recusandae reprehenderit, vero minus dolor quia.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut voluptatibus quo expedita molestias quidem deserunt ipsum dolorum unde esse, iste corporis sunt, iure ipsam, nihil quos labore magni quisquam atque.</p>

    <p>Again, Welcome. We hope your experience is a pleasant one.</p>

    <p>The AssetPost Team</p>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block head_title %}AssetPost{% endblock %}

templates/list_template.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy postsearch_form postsearch_form.helper %}

{% csrf_token %}




		{% block head_content %}
        <script src="{% static 'js/bootstrap-table.js' %}"></script>
        <script>
        function dateSorter(a, b) {
            a = Date.parse(a).getTime()/1000;
            b= Date.parse(b).getTime()/1000;
            return (a-b);
        }
        </script>
        <style>
        .fixed-table-container {
            border: 0 solid #dddddd;
            font-size: .9em;
        }
        .fixed-table-container tbody td {
            border: 0 solid #dddddd;
        }
        #page_table{font-size: .9em;border: 0 solid #dddddd;}
        .bootstrap-table .table, .bootstrap-table .table > tbody > tr > th, .bootstrap-table .table > tfoot > tr > th, .bootstrap-table .table > thead > tr > td, .bootstrap-table .table > tbody > tr > td, .bootstrap-table .table > tfoot > tr > td {
            padding: 0px 2px !important; border: 0 solid #dddddd;
        }
        .fixed-table-container thead th .th-inner {
            line-height: 1;
        }
        .fixed-table-container thead th {
            border-left: 0 solid #dddddd;
        }
        .fixed-table-container thead th {
            border-left: 0px solid #dddddd;
        }
        .bootstrap-table .table > thead > tr > th {
            border-bottom: 0px solid #ddd;
        }

        summary::-webkit-details-marker {
            color:blue;
        }

        details[open] summary::-webkit-details-markeblue#0000FF;
        }
        </style>
        <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/json2/20140204/json2.min.js"></script>
    <![endif]-->
		{% endblock %}


{% block content %}
	<iframe id="inbox_frame" src="" width="100%" height="100%"></iframe>
	<div id="list_controls" class="container stage">
		<div class="row searchform">
			<div class="col-md-12">
				<div class="well">
					
                    {% crispy form %}
                   <!-- <details>
                        <summary>Page Information</summary>
                        <p>Entering a client name or job number in the main search field yields post pages and records associated with your search term. 
                        <p>Entering a valid job number in the upper search field enables the QuckPost module, while entering a job number in the upper search field AND choosing a client from the pulldown menu will enable the Multipost module. 
                        <p>Finally, track your specific tasks via the Taskmanager module.
                    </details> -->
                    
				</div>
			</div>
		</div>
		<div class="row">
				{% if records or cellrecords %}
	   		<div class="col-md-5">
	   			<div class="well">
                  <h4>pages</h4> 
                    <table  
                            data-toggle="table"  
                            data-query-params="queryParams"
                            data-pagination="true"
                            data-search="true">
                        <thead>
                            <tr>
                                <th data-field="client"  data-sortable="true">client</th>
                                <th data-field="id"  data-sortable="true">id</th>
                                <th data-field="name"  data-sortable="true">name</th>
                                <th data-field="created" data-sorter="dateSorter">created</th>
                                <th data-field="edit"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for record in records %}
                            <tr>
                                <td>{{ record.client }}</td>
                                <td>{{ record.job_number }}</td>
                                <td><a href="{% url 'display_record' record.job_number %}" target="_blank">{{ record.job_name }}</a></td>
                                <td>{{ record.create_date }}</td>
                                <td><a href="{% url 'assetpost:updatePage' record.id %}"><input type="button" value="edit" class="list_tb_btn" /></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>  
		 		</div>
		 	</div>
			<div class="col-md-7">
	   			<div class="well">
                  <h4>entries</h4>
					<table  
                            data-toggle="table"  
                            data-query-params="queryParams"
                            data-pagination="true"
                            data-search="true">
                        <thead>
                            <tr>
                                <th data-field="client"  data-sortable="true">client</th>
                                <th data-field="id"  data-sortable="true">id</th>
                                <th data-field="cell"  data-sortable="true">cell</th>
                                <th data-field="name"  data-sortable="true">name</th>
                                <th data-field="type" data-sortable="true">type</th>
                                <th data-field="round" data-sortable="true">round</th>
                                <th data-field="created" data-sorter="dateSorter">created</th>
                                <th data-field="edit"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cellrecord in cellrecords %}
                            <tr>
                                <td>{{ cellrecord.client }}</td>
                                <td>{{ cellrecord.job_number }}</td>
                                <td>{{ cellrecord.cell_number }}</td>
                                <td><a href="{% url 'display_record' cellrecord.job_number %}" target="_blank">{{ cellrecord.post_title }}</a></td>
                                <td>{{ cellrecord.post_type }}</td>
                                <td>{{ cellrecord.post_round }}</td>
                                <td>{{ cellrecord.date }}</td>
                                <td><a href="{% url 'assetpost:updateEntry' cellrecord.id %}"><input type="button" value="edit" class="list_tb_btn" /></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    

                    <script>
                    var $table = $('#table');

                    $(function () {
                    });
                    function queryParams() {
                        return {
                            type: 'owner',
                            sort: 'updated',
                            direction: 'desc',
                            per_page: 100,
                            page: 1
                        };
                    }
                    </script>
                        

                </div>
            </div>
		{% else %}
		{% endif %}
			
		</div>	
			  
    </div>
{% endblock %}